### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by foxriver76** [OpenXbox/xbox-smartglass-core-node#37]
Hey, just started a new try to port from Python Rest Server to your nodejs WebAPI and Smartglass module. Discovery and connection works flawlessly, however after only a few seconds the process crashes with the following exception:

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 12. Received 16
--
at boundsError (internal/buffer.js:49:9)
at Buffer.readUInt32BE (internal/buffer.js:192:5)
at Object.readUInt32  (/opt/iobroker/node_modules/iobroker.xbox/node_modules/xbox-smartglass-core-node/src/packet/structure.js:111:37)
at Object.unpack  (/opt/iobroker/node_modules/iobroker.xbox/node_modules/xbox-smartglass-core-node/src/packet/message.js:38:51)
at Object.unpack  (/opt/iobroker/node_modules/iobroker.xbox/node_modules/xbox-smartglass-core-node/src/packet/message.js:174:64)
at Object.unpack  (/opt/iobroker/node_modules/iobroker.xbox/node_modules/xbox-smartglass-core-node/src/packet/message.js:480:80)
at Object.unpack  (/opt/iobroker/node_modules/iobroker.xbox/node_modules/xbox-smartglass-core-node/src/packet/packer.js:49:30)
at EventEmitter. (/opt/iobroker/node_modules/iobroker.xbox/node_modules/xbox-smartglass-core-node/src/events.js:19:32)
at EventEmitter.emit (events.js:198:13)
at Object. (/opt/iobroker/node_modules/iobroker.xbox/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
```

**Comment by foxriver76** [comment]
Okay, this only seems to happen if I try to connect while already being connected with this client. So more or less my fault, however it could be catched and a more meaningful error message may be possible.

**Comment by unknownskl** [comment]
Thanks for the report. Any pointers at how to reproduce the issue?
I am unable to reproduce it but it looks like there is something going wrong in the decryption of the packets.

**Comment by foxriver76** [comment]
I think I have created an instance of sgClient and called the `connect` method multiple times inside an interval.
